server:
  port: 8401
spring:
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.168.129:8848
      config:
        server-addr: http://192.168..168.129:8848
        file-extension: yaml
logging:
  level:
    root: debug